### ISSUE TITLE
Loop support and updates

### ISSUE THREAD

**Issue by eros71-dev** [dylanpdx/SM64Mus#5]
Is there any chance this project will get a future update with looping support?
Sorry to bother you, just wanted to know if this project was "dead" or you had any plans to update it eventually.

**Comment by dylanpdx** [comment]
I have vague plans to update it in the future with a new sound engine, but I'm not sure how soon it'll be as I'm pretty busy lately

**Comment by eros71-dev** [comment]
Alrighty, thanks
